### ISSUE TITLE
Unable to see Petri Net Visualization

### ISSUE THREAD

**Issue by FlorianDue** [iml130/swap-it-dashboard#3]
I set up a docker-compose project, where i execute processes with the PFDL-scheduler. For Visualization, I added this dashboard, however, the illustration of the Petri Net is not shown:

![petri-net](https://github.com/user-attachments/assets/fdfffbad-dc15-4864-bd05-72183348f16e)

The Project is public and can be found here:

https://github.com/swap-it/demo-scenario

To reproduce the error, execute the docker-compose prject:

git clone https://github.com/swap-it/demo-scenario.git
cd demo-scenario
docker-compose up

**Comment by OliverStolzBO** [comment]
It looks like the "bundle.js" and the "dotparser_worker.js" are missing in the dashboard's 'static/js/' directory. To build the latter, you need to run `npm run browserify` after `npm install` in the Dockerfile. The bundle.js needs to be inserted manually into the repository. Download it from the latest release of the pfdl-vs-code-extension [here](https://github.com/iml130/pfdl-vscode-extension/releases/download/v0.1.2/bundle.js).
